# IMMA.16832.S8.S8 combined bench → Accel-Sim -tensor_rate_per_cycle / -tensor_latency
SRC = config_tensor_imma16832.cu
EXE = config_tensor_imma16832

include ../../../common/common.mk
include ../../../common/imma16832.mk
